# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Asu0LF160cyqZrN_bpX70puAm2RTxRg
"""

!pip -q install playwright aiohttp nest_asyncio
!playwright install --with-deps chromium

!pip install playwright aiohttp
!playwright install chromium

import asyncio
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup
import aiohttp

BASE = "https://www.jurnaltv.md"
CATEGORY = "https://www.jurnaltv.md/category/zero-doi-tv"
MAX_PAGES = 12
CONCURRENCY = 12
OUTDIR = Path("/content/downloaded_images")

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Referer": BASE,
}

def category_page(n: int) -> str:
    return CATEGORY if n == 1 else f"{CATEGORY}/{n}"

def get_article_links() -> list[str]:
    links = []
    seen = set()
    for pg in range(1, MAX_PAGES + 1):
        url = category_page(pg)
        r = requests.get(url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")
        for a in soup.select("a[href*='/news/']"):
            href = a.get("href") or ""
            full = urljoin(BASE, href)
            if "/news/" in full and full not in seen:
                seen.add(full)
                links.append(full)
        print(f"page {pg:02d}: total articles {len(links)}")
    return links

def get_og_image(article_url: str) -> str | None:
    try:
        r = requests.get(article_url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")
        tag = soup.select_one("meta[property='og:image']")
        if tag:
            img = tag.get("content")
            if img and img.startswith("http"):
                return img
    except Exception as e:
        print("article err:", article_url, e)
    return None

async def download_one(session: aiohttp.ClientSession, sem: asyncio.Semaphore, url: str, dest: Path):
    async with sem:
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=60)) as resp:
                if resp.status == 200:
                    dest.write_bytes(await resp.read())
                    print("OK", dest.name)
                else:
                    print("HTTP", resp.status, url)
        except Exception as e:
            print("ERR", url, e)

async def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)

    print("[1/3] collecting article links...")
    articles = get_article_links()
    print("articles:", len(articles))

    print("\n[2/3] extracting og:image...")
    images = []
    for i, a in enumerate(articles, 1):
        img = get_og_image(a)
        if img:
            images.append(img)
        if i % 20 == 0:
            print(f"  processed {i}/{len(articles)} | images {len(images)}")

    images = list(dict.fromkeys(images))
    print("\nimages:", len(images))

    print("\n[3/3] downloading...")
    sem = asyncio.Semaphore(CONCURRENCY)
    async with aiohttp.ClientSession(headers=HEADERS) as session:
        tasks = []
        for i, img_url in enumerate(images, 1):
            clean = img_url.split("?")[0]
            ext = Path(urlparse(clean).path).suffix or ".jpg"
            dest = OUTDIR / f"image_{i:04d}{ext}"
            tasks.append(download_one(session, sem, img_url, dest))
        await asyncio.gather(*tasks)

    print("\nSaved to:", OUTDIR)
    print("Files:", len(list(OUTDIR.glob('image_*'))))

await main()

!zip -r /content/downloaded_images.zip /content/downloaded_images > /dev/null

from google.colab import files
files.download("/content/downloaded_images.zip")

!pip -q install trafilatura

import json, re, time
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup
import trafilatura
import tiktoken

BASE = "https://www.jurnaltv.md"
OUT_JSON = Path("/content/jurnaltv_articles_70k.json")

MIN_TOKENS = 70_000
MAX_CATEGORY_PAGES = 300
SLEEP = 0.25

HEADERS = {"User-Agent": "Mozilla/5.0"}
enc = tiktoken.get_encoding("cl100k_base")


def clean(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def get_html(url: str) -> str | None:
    try:
        r = requests.get(url, headers=HEADERS, timeout=30, allow_redirects=True)
        if r.status_code != 200:
            return None
        return r.text
    except Exception:
        return None


def find_categories() -> list[str]:
    """Берём категории с главной/меню: /category/..."""
    html = get_html(BASE)
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")

    cats = []
    for a in soup.select("a[href*='/category/']"):
        href = a.get("href") or ""
        u = urljoin(BASE, href)
        if "/category/" in u:
            u = u.split("#")[0].split("?")[0].rstrip("/")
            cats.append(u)

    cats = list(dict.fromkeys(cats))
    return cats


def category_page_url(cat: str, n: int) -> str:
    return cat if n == 1 else f"{cat}/{n}"


def extract_news_links_from_listing(url: str) -> list[str]:
    html = get_html(url)
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")

    links = []
    for a in soup.select("a[href*='/news/']"):
        href = a.get("href") or ""
        u = urljoin(url, href)
        if "/news/" in u:
            u = u.split("#")[0].split("?")[0]
            links.append(u)

    return list(dict.fromkeys(links))


def extract_article(url: str) -> dict | None:
    html = get_html(url)
    if not html:
        return None

    soup = BeautifulSoup(html, "html.parser")

    title = ""
    h1 = soup.select_one("h1")
    if h1:
        title = clean(h1.get_text(" ", strip=True))
    elif soup.title:
        title = clean(soup.title.get_text(" ", strip=True))

    text = trafilatura.extract(
        html,
        favor_precision=True,
        include_comments=False,
        include_tables=False,
        include_formatting=False,
    )
    if not text:
        return None

    text = text.strip()
    if len(text) < 200:
        return None

    return {"заголовок": title, "текст_статьи": text}


def count_tokens(item: dict) -> int:
    return len(enc.encode((item.get("заголовок") or "") + "\n" + (item.get("текст_статьи") or "")))


cats = find_categories()
print("Categories found:", len(cats))
for c in cats[:10]:
    print(" -", c)
if len(cats) > 10:
    print(" ...")

seen_articles = set()
articles = []
total_tokens = 0

print("\nCollecting /news/ links from categories and parsing until 70k tokens...")

for ci, cat in enumerate(cats, 1):
    if total_tokens >= MIN_TOKENS:
        break

    print(f"\n[CAT {ci}/{len(cats)}] {cat}")

    empty_pages = 0
    for pg in range(1, MAX_CATEGORY_PAGES + 1):
        page_url = category_page_url(cat, pg)
        links = extract_news_links_from_listing(page_url)

        if not links:
            empty_pages += 1
            if empty_pages >= 2:
                print(f"  page {pg}: no links (stop category)")
                break
            continue
        empty_pages = 0

        new_links = [u for u in links if u not in seen_articles]
        print(f"  page {pg}: links {len(links)} | new {len(new_links)} | tokens {total_tokens:,}")

        for u in new_links:
            seen_articles.add(u)
            art = extract_article(u)
            if not art:
                continue

            total_tokens += count_tokens(art)
            articles.append(art)

            if len(articles) % 10 == 0:
                print(f"    -> saved {len(articles)} | tokens {total_tokens:,}")

            if total_tokens >= MIN_TOKENS:
                break

            time.sleep(SLEEP)

        if total_tokens >= MIN_TOKENS:
            break

OUT_JSON.write_text(json.dumps(articles, ensure_ascii=False, indent=2), encoding="utf-8")
print("\nDONE")
print("Articles:", len(articles))
print("Tokens:", f"{total_tokens:,}")
print("Saved:", OUT_JSON)

from google.colab import files
files.download("/content/jurnaltv_articles_70k.json")