# -*- coding: utf-8 -*-
"""photo_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Asu0LF160cyqZrN_bpX70puAm2RTxRg
"""

!pip -q install playwright aiohttp nest_asyncio

!pip install playwright aiohttp
!playwright install chromium

import asyncio
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup
import aiohttp

BASE = "https://www.jurnaltv.md"
CATEGORY = "https://www.jurnaltv.md/category/zero-doi-tv"
MAX_PAGES = 12
CONCURRENCY = 12
OUTDIR = Path("/content/downloaded_images")

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Referer": BASE,
}

def category_page(n: int) -> str:
    return CATEGORY if n == 1 else f"{CATEGORY}/{n}"

def get_article_links() -> list[str]:
    links = []
    seen = set()
    for pg in range(1, MAX_PAGES + 1):
        url = category_page(pg)
        r = requests.get(url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")
        for a in soup.select("a[href*='/news/']"):
            href = a.get("href") or ""
            full = urljoin(BASE, href)
            if "/news/" in full and full not in seen:
                seen.add(full)
                links.append(full)
        print(f"page {pg:02d}: total articles {len(links)}")
    return links

def get_og_image(article_url: str) -> str | None:
    try:
        r = requests.get(article_url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")
        tag = soup.select_one("meta[property='og:image']")
        if tag:
            img = tag.get("content")
            if img and img.startswith("http"):
                return img
    except Exception as e:
        print("article err:", article_url, e)
    return None

async def download_one(session: aiohttp.ClientSession, sem: asyncio.Semaphore, url: str, dest: Path):
    async with sem:
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=60)) as resp:
                if resp.status == 200:
                    dest.write_bytes(await resp.read())
                    print("OK", dest.name)
                else:
                    print("HTTP", resp.status, url)
        except Exception as e:
            print("ERR", url, e)

async def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)

    print("[1/3] collecting article links...")
    articles = get_article_links()
    print("articles:", len(articles))

    print("\n[2/3] extracting og:image...")
    images = []
    for i, a in enumerate(articles, 1):
        img = get_og_image(a)
        if img:
            images.append(img)
        if i % 20 == 0:
            print(f"  processed {i}/{len(articles)} | images {len(images)}")

    images = list(dict.fromkeys(images))
    print("\nimages:", len(images))

    print("\n[3/3] downloading...")
    sem = asyncio.Semaphore(CONCURRENCY)
    async with aiohttp.ClientSession(headers=HEADERS) as session:
        tasks = []
        for i, img_url in enumerate(images, 1):
            clean = img_url.split("?")[0]
            ext = Path(urlparse(clean).path).suffix or ".jpg"
            dest = OUTDIR / f"image_{i:04d}{ext}"
            tasks.append(download_one(session, sem, img_url, dest))
        await asyncio.gather(*tasks)

    print("\nSaved to:", OUTDIR)
    print("Files:", len(list(OUTDIR.glob('image_*'))))

await main()

!zip -r /content/downloaded_images.zip /content/downloaded_images > /dev/null

from google.colab import files
files.download("/content/downloaded_images.zip")

