# -*- coding: utf-8 -*-
"""text_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nq9hFEI7Ww5_k-gFEBxm6l3kMQFuPrPb
"""

!pip -q install trafilatura

import json, re, time
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup
import trafilatura
import tiktoken

BASE = "https://www.jurnaltv.md"
out_json = Path("/content/jurnaltv_articles_70k.json")

min_tokens = 70_000
max_category_pages = 300
sleep = 0.25

HEADERS = {"User-Agent": "Mozilla/5.0"}
enc = tiktoken.get_encoding("cl100k_base")


def clean(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def get_html(url: str) -> str | None:
    try:
        r = requests.get(url, headers=HEADERS, timeout=30, allow_redirects=True)
        if r.status_code != 200:
            return None
        return r.text
    except Exception:
        return None


def find_categories() -> list[str]:
    html = get_html(BASE)
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")

    cats = []
    for a in soup.select("a[href*='/category/']"):
        href = a.get("href") or ""
        u = urljoin(BASE, href)
        if "/category/" in u:
            u = u.split("#")[0].split("?")[0].rstrip("/")
            cats.append(u)

    cats = list(dict.fromkeys(cats))
    return cats


def category_page_url(cat: str, n: int) -> str:
    return cat if n == 1 else f"{cat}/{n}"


def extract_news_links_from_listing(url: str) -> list[str]:
    html = get_html(url)
    if not html:
        return []
    soup = BeautifulSoup(html, "html.parser")

    links = []
    for a in soup.select("a[href*='/news/']"):
        href = a.get("href") or ""
        u = urljoin(url, href)
        if "/news/" in u:
            u = u.split("#")[0].split("?")[0]
            links.append(u)

    return list(dict.fromkeys(links))


def extract_article(url: str) -> dict | None:
    html = get_html(url)
    if not html:
        return None

    soup = BeautifulSoup(html, "html.parser")

    title = ""
    h1 = soup.select_one("h1")
    if h1:
        title = clean(h1.get_text(" ", strip=True))
    elif soup.title:
        title = clean(soup.title.get_text(" ", strip=True))

    text = trafilatura.extract(
        html,
        favor_precision=True,
        include_comments=False,
        include_tables=False,
        include_formatting=False,
    )
    if not text:
        return None

    text = text.strip()
    if len(text) < 200:
        return None

    return {"заголовок": title, "текст_статьи": text}


def count_tokens(item: dict) -> int:
    return len(enc.encode((item.get("заголовок") or "") + "\n" + (item.get("текст_статьи") or "")))


cats = find_categories()
print("Categories found:", len(cats))
for c in cats[:10]:
    print(" -", c)
if len(cats) > 10:
    print(" ...")

seen_articles = set()
articles = []
total_tokens = 0

print("\nCollecting /news/ links from categories and parsing until 70k tokens...")

for ci, cat in enumerate(cats, 1):
    if total_tokens >= min_tokens:
        break

    print(f"\n[CAT {ci}/{len(cats)}] {cat}")

    empty_pages = 0
    for pg in range(1, max_category_pages + 1):
        page_url = category_page_url(cat, pg)
        links = extract_news_links_from_listing(page_url)

        if not links:
            empty_pages += 1
            if empty_pages >= 2:
                print(f"  page {pg}: no links (stop category)")
                break
            continue
        empty_pages = 0

        new_links = [u for u in links if u not in seen_articles]
        print(f"  page {pg}: links {len(links)} | new {len(new_links)} | tokens {total_tokens:,}")

        for u in new_links:
            seen_articles.add(u)
            art = extract_article(u)
            if not art:
                continue

            total_tokens += count_tokens(art)
            articles.append(art)

            if len(articles) % 10 == 0:
                print(f"-> saved {len(articles)} | tokens {total_tokens:,}")

            if total_tokens >= min_tokens:
                break

            time.sleep(sleep)

        if total_tokens >= min_tokens:
            break

out_json.write_text(json.dumps(articles, ensure_ascii=False, indent=2), encoding="utf-8")
print("\nDONE")
print("Articles:", len(articles))
print("Tokens:", f"{total_tokens:,}")
print("Saved:", out_json)

from google.colab import files
files.download("/content/jurnaltv_articles_70k.json")

